#!/bin/bash

# cd scripts

# mkdir test_result

image_name=cloudamqp-rabbitmq-server-stack-terratest
image_version=2.24.0


docker run \
    -v /home/williannap/Documents/repos/test-project/terratest-packager/test_result:/opt/test/result ${image_name}:${image_version}


# # docker run  ${image_name}:${image_version}

# test / mkdir result / 


# LIST_FOLDERS="Desktop Documents Downloads go Music Pictures Public snap Templates trash Videos"


# if [[ -z "${LIST_FOLDERS}" ]]; then
#     echo "não tem nada"
# fi 