#!/bin/bash
source "${TF_PACKAGER_ENVIRONMENT_VARIABLES_FILE_NAME?}"

IMAGE_NAME=${STACK_NAME?}-terratest

mkdir test_result

PATH_TEST_FOLDER=$(pwd /test_result)

docker build \
  --rm \
  --tag "${STACK_NAME?}:latest" \
  --tag "${IMAGE_NAME?}" \
  "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}" 

docker run \
  -v ${PATH_TEST_FOLDER}/test_result:/opt/test/result ${IMAGE_NAME}:latest
  
CODE_EXIT="$?"

if [  "${CODE_EXIT-0}" != "0" ]; then
  exit "${CODE_EXIT}"
fi

docker system prune -f &> /dev/null
